### ISSUE TITLE
Something to do with chrome driver

### ISSUE THREAD

**Issue by pawan-xd** [TheFenrisLycaon/BlackBoard-Auto#6]
After entering Username and Password the program throws out this error. Could you guide me on how to fix this issue. I dont mind getting my hands dirty but i dont know where to start

```
Traceback (most recent call last):
  File "setup.py", line 176, in <module>
  File "setup.py", line 140, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 81, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 85

[2836] Failed to execute script setup
```

**Comment by TheFenrisLycaon** [comment]
The chromedriver version is incompatible with the one you have installed. 

Steps to fix :
- Go to chrome. 
- Click on about.
- verify chrome version
- Goto https://chromedriver.chromium.org/downloads.
- Download the required version.
